[tool.mypy]
ignore_missing_imports = true
pretty = true
show_error_codes = true
show_error_context = true

[tool.ruff]
select = [
    "AIR",    # Airflow
    "ASYNC",  # flake8-async
    "C90",    # McCabe cyclomatic complexity
    "CPY",    # flake8-copyright
    "DJ",     # flake8-django
    "E",      # pycodestyle errors
    "F",      # Pyflakes
    "FA",     # flake8-future-annotations
    "FLY",    # flynt
    "I",      # isort
    "ICN",    # flake8-import-conventions
    "INT",    # flake8-gettext
    "NPY",    # NumPy-specific rules
    "PD",     # pandas-vet
    "PIE",    # flake8-pie
    "PL",     # Pylint
    "PYI",    # flake8-pyi
    "RSE",    # flake8-raise
    "SLOT",   # flake8-slots
    "T10",    # flake8-debugger
    "TCH",    # flake8-type-checking
    "TID",    # flake8-tidy-imports
    "UP",     # pyupgrade
    "W",      # pycodestyle warnings
    "YTT",    # flake8-2020
    # "A",    # flake8-builtins
    # "ANN",  # flake8-annotations
    # "ARG",  # flake8-unused-arguments
    # "B",    # flake8-bugbear
    # "BLE",  # flake8-blind-except
    # "C4",   # flake8-comprehensions
    # "COM",  # flake8-commas
    # "D",    # pydocstyle
    # "DTZ",  # flake8-datetimez
    # "EM",   # flake8-errmsg
    # "ERA",  # eradicate
    # "EXE",  # flake8-executable
    # "FBT",  # flake8-boolean-trap
    # "FIX",  # flake8-fixme
    # "G",    # flake8-logging-format
    # "INP",  # flake8-no-pep420
    # "ISC",  # flake8-implicit-str-concat
    # "N",    # pep8-naming
    # "PERF", # Perflint
    # "PGH",  # pygrep-hooks
    # "PT",   # flake8-pytest-style
    # "PTH",  # flake8-use-pathlib
    # "Q",    # flake8-quotes
    # "RET",  # flake8-return
    # "RUF",  # Ruff-specific rules
    # "S",    # flake8-bandit
    # "SIM",  # flake8-simplify
    # "SLF",  # flake8-self
    # "T20",  # flake8-print
    # "TD",   # flake8-todos
    # "TRY",  # tryceratops
]
ignore = [
    "E402",
    "E731",
    "F811",
    "F841",
    "PLE1205",
    "PLR1714",
    "PLR5501",
    "PLW0120",
    "PLW0602",
    "PLW0603",
    "PLW2901",
    "UP03",
]
line-length = 146
target-version = "py311"

[tool.ruff.mccabe]
max-complexity = 15  # default is 10

[tool.ruff.pylint]
allow-magic-value-types = ["int", "str"]
max-args = 10  # default is 5
max-branches = 16  # default is 12
max-returns = 6  # default is 6
max-statements = 50  # default is 50
